export interface BlogPost {
  slug: string;
  title: string;
  desc: string;
  category: "Marketing" | "SEO" | "AI" | "Web Design";
  readTime: string;
  date: string;
  content: string[];
  ogImage?: string;
}

export const posts: BlogPost[] = [
  {
    slug: "google-bans-employee-name-reviews-local-seo-2026",
    title: "Google Just Banned the Most Popular Review Strategy in Local Business. Here's What to Do This Week.",
    desc: "Google's April 2026 policy update bans asking customers to name employees in reviews. Here's what changed, why it matters, and the exact playbook to fix it this week.",
    category: "SEO",
    readTime: "6 min read",
    date: "April 17, 2026",
    ogImage: "/images/blogs/review/review_change.png",
    content: [
      "If your business has ever asked a customer to \"mention [employee name] in your review,\" that ask is now against Google's policy.",
      "The update hit on April 17, 2026, and most business owners still haven't heard about it. The ones who have are quietly panicking, because reviews mentioning employee names are already starting to get removed.",
      "Here's what changed, why it matters, and the exact playbook to fix it before your review count starts dropping.",
      "## What Google Actually Changed",
      "Google added two new clauses to its Maps Rating Manipulation policy, both of which target how merchants direct their staff to collect reviews.",
      "The new prohibited practices are directing staff to hit a specific number of reviews in a given period (quotas), and directing staff to ask customers to include specific content in a review, including employee names. That second clause is the one that blows up the playbook most local service businesses have been running for years.",
      "## The Playbook That Just Died",
      "If you've spent any time in local marketing, you already know the tactics. The \"Ask for Mike, he's the best!\" review scripts. The $25 to $50 bonuses for every review that mentions a tech's name. The office whiteboards tracking named-review counts by employee. The monthly review competitions between team members. The SMS follow-ups with pre-written copy telling customers to mention Sarah in their review.",
      "All of it worked. It pumped up review counts, boosted local rankings, and gave technicians a direct incentive to deliver great service. It's also all now a policy violation.",
      "The harder part is that Google isn't just ignoring these reviews for ranking purposes. Early reports from local SEO professionals show Google is actively removing reviews that appear templated, especially short ones that name a staff member. If 40% of your reviews say \"Ask for Mike!\", you could see a meaningful chunk of them disappear over the coming weeks.",
      "## Why This Hits Home Service Hardest",
      "Plumbers, HVAC companies, roofers, electricians, remodelers, cleaners, and landscapers all built their review strategy around named technicians. It made sense at the time. When a plumber shows up to your house, you remember their name, not the company's.",
      "That's exactly why Google flagged it. When 80% of a business's reviews follow the same pattern (\"Mike was great, ask for Mike!\"), Google's NLP detects it as scripted behavior rather than organic feedback.",
      "The same risk applies to any local service business: medspas, auto shops, dental offices, personal trainers, real estate agents. If your team has been trained to ask for name-drops, you're exposed.",
      "## What to Do This Week",
      "The fix takes about an hour to roll out across your business.",
      "First, kill the name-drop script. Go through every touchpoint where you ask for reviews, including SMS follow-ups, email templates, printed cards, QR code landing pages, and in-person scripts. Remove any language that tells the customer what to write.",
      "Second, restructure your employee incentives. Stop paying bonuses tied to named reviews. Pay for any 5-star review instead, or tie bonuses to overall job performance metrics like CSAT scores.",
      "Third, write a new review ask template. Replace \"mention Mike in your review\" with something like: \"If you have 30 seconds, a quick review about the [service] we did today in [city] would really help us out.\"",
      "This gets you the ranking juice without the risk. Reviews that describe the actual service and location are worth more than named reviews ever were, because Google reads those keywords and uses them to match your profile to relevant local searches.",
      "Fourth, audit your existing reviews. You don't need to delete anything, but you should know where you stand. Count how many of your reviews follow the \"name + short compliment\" pattern, because those are your at-risk reviews.",
      "Fifth, never put a tablet at the checkout counter. In a separate policy update from the same week, Google also prohibited merchants from pressuring customers to leave reviews while on the premises. The in-lobby iPad kiosk is officially dead.",
      "## The Bigger Picture",
      "Reviews are still the single biggest lever in local SEO. Nothing moves Google Map Pack rankings faster, nothing builds trust with a potential customer faster, and nothing compounds over time the way a healthy review system does. What's changing here is how you're allowed to collect them.",
      "The businesses that update their systems this month are going to win. The ones who keep running the old scripts are gambling with their review counts for a tactic that no longer carries any upside.",
      "At Driftlss, we rebuild local businesses' review systems to be fully compliant with the new policy and designed to actually rank. If you want us to audit yours for free, [reach out here](/contact).",
    ],
  },
  {
    slug: "why-parents-judge-your-practice-by-your-website",
    title: "Why 73% of Parents Judge Your Practice by Your Website",
    desc: "First impressions now outweigh referrals. Here's what families look for on your therapy practice website, and the mistakes that cost you patients every month.",
    category: "Marketing",
    readTime: "6 min read",
    date: "March 28, 2026",
    content: [
      "Your website is the first thing parents see — before they ever call your office, read a review, or ask a friend. And in 2026, that first impression carries more weight than a personal referral.",
      "A recent study found that 73% of parents form an opinion about a therapy practice within seconds of visiting their website. If the site looks outdated, loads slowly, or feels confusing, they leave. They don't call. They don't email. They just move on to the next result.",
      "## What Parents Actually Look For",
      "It's not about flashy animations or trendy design. Parents searching for therapy services — whether ABA, occupational therapy, speech, or sensory integration — have specific concerns. They want to know three things immediately: Can you help my child? Are you trustworthy? How do I get started?",
      "Your website needs to answer all three within the first few seconds of a visit. That means clear headlines that speak to their situation, real photos of your space and team, and an obvious path to book a consultation or call your office.",
      "## The Trust Gap Is Real",
      "Most therapy practice websites we audit have the same problems. Stock photos of generic kids. Walls of clinical text. Buried contact information. No clear call to action. These sites might have great information somewhere, but parents never find it because they've already bounced.",
      "The practices that win online are the ones that feel human. They show their actual facility. They introduce their therapists with real photos and genuine bios. They explain their approach in language parents understand — not clinical jargon.",
      "## Speed Matters More Than You Think",
      "Page load time is one of the biggest hidden killers of therapy practice websites. If your site takes more than 3 seconds to load, over half of mobile visitors will leave before they see a single word. Most therapy practice websites we encounter load in 6-8 seconds. That's a massive leak in your patient pipeline.",
      "Modern websites built on frameworks like Next.js load in under 2 seconds. The difference in conversion rates between a 2-second site and a 6-second site is dramatic — often a 2-3x improvement in form submissions and phone calls.",
      "## Mobile Is Not Optional",
      "Over 70% of parents researching therapy options are doing it on their phone. Usually during a break at work, after the kids are in bed, or in a waiting room. If your website doesn't work perfectly on a phone screen, you're invisible to the majority of your potential patients.",
      "Mobile-first design isn't a buzzword — it's a requirement. Every button needs to be tappable. Every form needs to be fillable with a thumb. Every piece of information needs to be readable without zooming.",
      "## What to Do About It",
      "The fix isn't complicated, but it does require intention. Start by looking at your own website on your phone. Try to book a consultation. Try to find your therapists' credentials. Try to understand what services you offer. If any of those tasks feel difficult, your potential patients feel the same way.",
      "The practices that invest in a clean, fast, mobile-first website see measurable results within weeks. More form submissions. More phone calls. More families walking through the door. It's not magic — it's just removing the friction between a parent's need and your ability to help.",
    ],
  },
  {
    slug: "what-is-geo-and-why-your-practice-needs-it",
    title: "What is GEO and Why Your Practice Needs It",
    desc: "Generative Engine Optimization explained for therapy practices. Learn how AI-powered search works and why your practice needs a GEO strategy right now.",
    category: "SEO",
    readTime: "7 min read",
    date: "March 25, 2026",
    content: [
      "The way families find therapy providers is changing fast. Google is still important, but a growing number of parents are turning to AI-powered tools — ChatGPT, Google's AI Overviews, Perplexity, and others — to research care options for their children.",
      "This shift has created an entirely new discipline: Generative Engine Optimization, or GEO. And if your practice isn't thinking about it, you're already falling behind.",
      "## How Families Search in 2026",
      "Traditional search works like this: a parent types \"ABA therapy near me\" into Google, scans the results, clicks a few links, and makes a decision. SEO has been the playbook for showing up in those results for over two decades.",
      "But now, many parents are asking AI assistants questions like \"What should I look for in an ABA therapy provider for my 4-year-old?\" or \"Best pediatric OT clinics in [city] with good reviews.\" These AI tools don't just show a list of links — they synthesize information and recommend specific providers.",
      "The question is: will your practice be one of the ones they recommend?",
      "## What GEO Actually Means",
      "Generative Engine Optimization is the practice of structuring your online presence so that AI systems can understand, trust, and recommend your practice. It's not about gaming an algorithm. It's about making your practice's information clear, authoritative, and accessible to both humans and AI.",
      "GEO involves several key areas. Your website content needs to be structured in a way AI can parse — clear headings, specific service descriptions, location information, and credentials. Your practice needs consistent information across the web — the same name, address, phone number, and service descriptions everywhere you appear.",
      "You also need authoritative content that demonstrates expertise. Blog posts, FAQ pages, and service descriptions that answer the actual questions parents are asking. When an AI tool is deciding which practices to recommend, it looks for depth of information and consistency of reputation.",
      "## The Difference Between SEO and GEO",
      "SEO optimizes for search engine rankings — getting your website to appear higher in Google's list of results. GEO optimizes for AI recommendations — getting your practice mentioned when an AI assistant is helping a parent make a decision.",
      "They're related but different. SEO focuses on keywords, backlinks, and technical site performance. GEO focuses on content structure, information consistency, and authoritative expertise signals. The good news is that many GEO practices also help your SEO. But GEO-specific strategies are becoming essential.",
      "## Why This Matters for Therapy Practices",
      "Therapy practices are uniquely positioned to benefit from GEO. Parents making decisions about their child's care do extensive research. They read, compare, and ask questions. AI tools are becoming a central part of that research process.",
      "Practices that show up in AI recommendations see a different kind of lead. These families have already been educated about what to look for. They arrive at your door more informed, more committed, and more likely to follow through with treatment.",
      "## Getting Started with GEO",
      "The first step is auditing your current online presence. Is your practice information consistent across Google Business Profile, your website, directories, and social media? Are your service descriptions clear and specific? Do you have content that answers the questions parents actually ask?",
      "From there, it's about building content that AI systems can trust. Detailed service pages. Thoughtful blog posts about common parent concerns. FAQ sections that address real questions. Therapist bios with credentials and specializations. Every piece of content you create is an opportunity to be discovered by the AI tools parents are increasingly relying on.",
    ],
  },
  {
    slug: "ai-chatbot-playbook-for-therapy-practices",
    title: "The AI Chatbot Playbook for Therapy Practices",
    desc: "How to answer parent questions 24/7 without hiring more staff. A complete step-by-step guide to deploying AI-powered intake at your therapy practice.",
    category: "AI",
    readTime: "8 min read",
    date: "March 22, 2026",
    content: [
      "Every therapy practice has the same problem: parents have questions at 9 PM on a Tuesday, and your front desk closed at 5. Those unanswered questions don't wait. Parents move on, find another provider, or simply give up on getting help for their child.",
      "AI chatbots solve this in a way that wasn't possible even two years ago. Not the clunky, scripted bots from the early 2020s that could barely handle \"What are your hours?\" — modern AI assistants that genuinely understand what a parent is asking and provide helpful, accurate responses.",
      "## Why Therapy Practices Need This",
      "The average therapy practice misses 30-40% of incoming inquiries. Phone calls go to voicemail. Contact forms sit in an inbox overnight. Website visitors leave without taking action because they had a question that wasn't answered on the page.",
      "An AI chatbot catches those missed opportunities. When a parent lands on your website at 10 PM wondering if you accept their insurance, the chatbot answers immediately. When someone wants to know what ABA therapy actually involves, the chatbot explains it in plain language. When a parent is ready to book, the chatbot walks them through the process.",
      "## What a Good Therapy Chatbot Looks Like",
      "The key word is \"good.\" A bad chatbot frustrates people and damages your reputation. A good chatbot feels like talking to a knowledgeable, empathetic member of your team.",
      "A good therapy practice chatbot knows your services inside and out. It understands the difference between your ABA program and your occupational therapy services. It knows your insurance policies, your intake process, and your scheduling availability. It answers questions in warm, parent-friendly language — not clinical jargon.",
      "It also knows its limits. When a parent asks something the chatbot can't answer with confidence, it captures their information and promises a follow-up from your team. This is critical. Parents need to feel heard, even when the AI can't fully resolve their question.",
      "## The Intake Funnel",
      "The most valuable thing a chatbot does isn't answering questions — it's qualifying and capturing leads. Here's how the funnel works:",
      "A parent visits your site and engages with the chatbot. Through natural conversation, the chatbot learns their child's age, their concerns, what services they're interested in, and their insurance situation. By the end of the conversation, the chatbot has collected their name, email, and phone number — and has enough context for your intake coordinator to have a productive follow-up call.",
      "This happens 24 hours a day, 7 days a week. No overtime. No missed calls. No leads falling through the cracks.",
      "## Setting Up Your Chatbot",
      "Implementation isn't as complex as it sounds. The process involves three phases:",
      "First, you build the knowledge base. This means documenting everything a parent might ask — services, insurance, scheduling, therapist credentials, facility details, intake process. The more thorough this foundation, the better your chatbot performs.",
      "Second, you train and test. The chatbot needs to handle edge cases gracefully. What if someone asks about a service you don't offer? What if they're in crisis? What if they're asking on behalf of a school district rather than as a parent? Testing these scenarios ensures your chatbot represents your practice well.",
      "Third, you integrate with your systems. The chatbot should feed captured leads directly into your CRM or intake system. No manual data entry. No leads lost in a chat transcript nobody reads.",
      "## Measuring Success",
      "The metrics that matter are simple: How many conversations happen after hours? How many leads are captured that would have otherwise been lost? What's the conversion rate from chatbot conversation to booked consultation?",
      "Most practices we work with see a 25-40% increase in qualified leads within the first month of deploying an AI chatbot. The ROI is immediate and measurable. And unlike hiring additional front desk staff, a chatbot scales without additional cost.",
    ],
  },
  {
    slug: "seo-vs-geo-whats-the-difference",
    title: "SEO vs GEO: What's the Difference?",
    desc: "Both SEO and GEO help families find your therapy practice, but they work very differently. Here's a clear breakdown of each strategy and why you need both.",
    category: "SEO",
    readTime: "5 min read",
    date: "March 19, 2026",
    content: [
      "If you've been marketing your therapy practice online, you've heard of SEO — Search Engine Optimization. It's been the foundation of online visibility for two decades. But there's a new acronym you need to know: GEO, or Generative Engine Optimization.",
      "Both help families find your practice. But they work differently, target different platforms, and require different strategies. Here's a clear breakdown.",
      "## SEO: The Foundation",
      "SEO is about ranking in traditional search engine results. When a parent searches \"pediatric occupational therapy in Milwaukee,\" SEO determines whether your practice appears on page one or page five of Google.",
      "SEO focuses on keywords — making sure your website mentions the terms parents search for. It focuses on technical performance — fast load times, mobile-friendly design, proper meta tags. And it focuses on authority — backlinks from other websites, positive reviews, and consistent business listings.",
      "SEO has been the standard playbook for years, and it still works. Google isn't going anywhere. Traditional search results still drive the majority of website traffic for most therapy practices.",
      "## GEO: The New Frontier",
      "GEO is about showing up in AI-generated responses. When a parent asks ChatGPT \"What are the best ABA therapy providers near me?\" or when Google's AI Overview summarizes therapy options, GEO determines whether your practice is mentioned.",
      "GEO focuses on content structure — making your information easy for AI systems to parse and understand. It focuses on consistency — ensuring your practice name, services, and details are identical everywhere online. And it focuses on authority signals — detailed, expert content that AI systems trust enough to recommend.",
      "The key difference: SEO gets you ranked in a list. GEO gets you recommended in a conversation.",
      "## Where They Overlap",
      "The good news is that SEO and GEO share a lot of common ground. High-quality content helps both. Fast, well-structured websites help both. Consistent business information helps both. Strong reviews and reputation help both.",
      "If you're already doing SEO well, you have a head start on GEO. Many of the fundamentals transfer directly.",
      "## Where They Diverge",
      "The differences matter. SEO rewards keyword density and backlink profiles. GEO rewards information depth and structured data. SEO targets specific search queries. GEO targets the broader questions and conversations parents have about therapy options.",
      "For example, an SEO strategy might focus on ranking for \"ABA therapy Chicago.\" A GEO strategy would also ensure your practice has detailed content about your ABA methodology, your therapists' training, your success metrics, and your intake process — because that's the kind of comprehensive information AI systems look for when making recommendations.",
      "## Why You Need Both",
      "Ignoring either one leaves money on the table. Parents who search traditionally need to find you through SEO. Parents who ask AI assistants for help need to find you through GEO. The practices that invest in both capture the full spectrum of how families discover care providers in 2026.",
      "The shift toward AI-powered search is accelerating. Practices that start building their GEO strategy now will have a significant advantage over those that wait. The best time to start was last year. The second-best time is today.",
    ],
  },
  {
    slug: "5-website-mistakes-every-therapy-practice-makes",
    title: "5 Website Mistakes Every Therapy Practice Makes",
    desc: "Five website mistakes we see on nearly every therapy practice site, with quick fixes for each that will improve your conversions and bring in more patients.",
    category: "Web Design",
    readTime: "5 min read",
    date: "March 15, 2026",
    content: [
      "After reviewing hundreds of therapy practice websites, the same problems show up over and over. These aren't minor design preferences — they're conversion killers that cost practices real patients every month.",
      "Here are the five most common mistakes and how to fix each one.",
      "## 1. No Clear Call to Action Above the Fold",
      "The most critical real estate on your website is the top of the homepage — what visitors see before scrolling. Most therapy practice sites waste this space with a generic welcome message or a stock photo slideshow.",
      "Parents who land on your site have a specific intent. They want to take the next step. If they can't immediately see how to book a consultation, call your office, or submit an inquiry, you've created unnecessary friction.",
      "The fix: Put a clear, specific call to action at the top of every page. Not \"Learn More\" — something actionable like \"Book a Free Consultation\" or \"Call Us Today.\" Make the button large, colored, and impossible to miss.",
      "## 2. Stock Photos Instead of Real Images",
      "Parents can spot stock photos instantly. When they see generic images of smiling children that clearly aren't from your facility, it erodes trust. They start wondering what you're hiding.",
      "Your actual space is your biggest asset. Real photos of your therapy rooms, your sensory gyms, your waiting area, and your team create an immediate emotional connection. Parents can picture their child in your space.",
      "The fix: Invest in a professional photo shoot of your facility and team. If budget is tight, even well-lit smartphone photos of your real space outperform stock imagery. Authenticity always wins.",
      "## 3. Clinical Jargon Everywhere",
      "Your website isn't written for other therapists — it's written for worried parents. Terms like \"sensory integration dysfunction,\" \"applied behavior analysis protocols,\" and \"proprioceptive input\" mean nothing to most families.",
      "Parents want to know: Will you help my child? What will sessions look like? How long until we see progress? Answer those questions in plain language.",
      "The fix: Rewrite your service descriptions from the parent's perspective. Lead with the problem they're experiencing, then explain how you solve it. Save the clinical details for a deeper page aimed at referral sources.",
      "## 4. Buried or Missing Contact Information",
      "This one seems obvious, but it's shockingly common. We regularly find therapy practice websites where the phone number is only on the Contact page. Where the contact form is broken. Where there's no email address listed at all.",
      "Every page of your website should make it easy to get in touch. If a parent has to hunt for your phone number, many won't bother.",
      "The fix: Put your phone number and a \"Book a Consultation\" button in your navigation header. Add a contact section to the bottom of every page. Make your phone number clickable on mobile so parents can call with one tap.",
      "## 5. Slow Load Times",
      "Most therapy practice websites are built on WordPress with heavy themes, unoptimized images, and cheap shared hosting. The result: 5-8 second load times that drive away more than half of mobile visitors.",
      "Parents don't wait for slow websites. If your site doesn't load in 2-3 seconds, they're hitting the back button and clicking the next result.",
      "The fix: Optimize your images, minimize unnecessary plugins, and consider migrating to modern hosting. Better yet, rebuild on a modern framework like Next.js that delivers sub-2-second load times out of the box. The performance difference alone can double your conversion rate.",
    ],
  },
  {
    slug: "how-to-showcase-your-team-online",
    title: "How to Showcase Your Team Online",
    desc: "How to build a therapy team page that converts browsers into callers. What parents want to see in bios, credentials, and photos before picking up the phone.",
    category: "Marketing",
    readTime: "6 min read",
    date: "March 12, 2026",
    content: [
      "When parents are choosing a therapy provider for their child, the team page is often the most visited page on the entire website — right after the homepage. Parents aren't just looking for a practice. They're looking for a person they can trust with their child.",
      "Most therapy practice websites treat the team page as an afterthought. A headshot, a name, a list of credentials. Maybe a sentence about interests outside of work. That's a missed opportunity.",
      "## Why the Team Page Matters So Much",
      "Choosing a therapist is one of the most personal decisions a parent makes. They're looking for someone who will understand their child, connect with their family, and guide them through a process that can feel overwhelming.",
      "Your team page is where that trust begins. It's where parents decide if they feel comfortable calling your office. A strong team page can be the difference between a parent booking a consultation and continuing their search.",
      "## What Parents Actually Want to See",
      "Through conversations with hundreds of families, we've learned what parents look for on a team page. It comes down to three things: competence, warmth, and relatability.",
      "Competence means credentials and experience. Parents want to know your therapists are qualified. But they don't want a wall of acronyms. They want to understand what those credentials mean for their child's care. Instead of just listing \"BCBA, M.Ed.,\" explain what that means: \"Board Certified Behavior Analyst with a Master's in Education — specializing in early intervention for children ages 2-6.\"",
      "Warmth means personality. A genuine smile in a photo. A bio written in first person. Something that makes the therapist feel like a real person, not a clinical profile. Parents are looking for someone their child will like spending time with.",
      "Relatability means connection points. Why did this person become a therapist? What do they love about working with kids? Do they have children of their own? These details create emotional bridges that clinical credentials alone can't build.",
      "## Writing Better Bios",
      "The best therapist bios follow a simple structure. Start with their specialty and experience — what they do and how long they've been doing it. Then share their approach — how they work with children and what parents can expect. Finally, add a personal touch — something that makes them human.",
      "Write in first person when possible. \"I've been working with children on the autism spectrum for 8 years\" is more engaging than \"Sarah has 8 years of experience working with children on the autism spectrum.\" First person creates a sense of direct conversation with the parent reading the bio.",
      "Keep bios concise but meaningful. Three to four paragraphs is the sweet spot. Long enough to build trust, short enough to be read in full.",
      "## Photos Make or Break It",
      "A professional headshot is non-negotiable. But the best team pages go further. Include photos of therapists in action — working with children in your therapy space, engaging in activities, showing the genuine warmth that defines great therapists.",
      "Avoid overly formal corporate headshots. Parents aren't hiring a lawyer. They want to see friendly, approachable people who their child will enjoy being around. Natural lighting, genuine smiles, and a setting that reflects your practice's personality.",
      "## Beyond the Team Page",
      "Your team's presence shouldn't be limited to one page. Feature therapists on your homepage. Include therapist spotlights in your blog content. Share team moments on social media. The more touchpoints parents have with your team before they call, the more likely they are to follow through.",
      "Consistent visibility of your team across your entire digital presence builds familiarity and trust. When a parent finally picks up the phone, they should already feel like they know who they're going to be working with.",
    ],
  },
  {
    slug: "wordpress-vs-nextjs-ai-citations-health-study",
    title: "We Tested 99 Health Websites Across ChatGPT, Claude, and Google AI Overviews. Here's What We Found About WordPress vs Next.js.",
    desc: "Next.js sites captured 70% of all AI citations in our study of 99 health websites. We break down why — and what it means for your GEO strategy.",
    category: "AI",
    readTime: "10 min read",
    date: "April 9, 2026",
    content: [
      "AI is eating search. Google AI Overviews now sit above organic results for most health queries. ChatGPT and Claude are becoming the first place people go to find a doctor, choose a fitness app, or compare telehealth platforms. The question every health brand should be asking isn't \"how do I rank on Google?\" anymore — it's \"how do I get cited by AI?\"",
      "We wanted to know: does your tech stack actually matter? Specifically, do Next.js sites have an edge over WordPress when it comes to Generative Engine Optimization (GEO)?",
      "So we ran a study. 99 health industry websites. 49 built on Next.js, 50 on WordPress. 25 real health queries. Three AI platforms. Here's what the data says.",
      "## The Headline Numbers",
      "Next.js sites captured 70% of all AI citations across ChatGPT, Claude, and Google AI Overviews. Out of 163 total study site mentions, 114 went to Next.js sites and 49 went to WordPress.",
      "But the gap goes deeper than raw counts:",
      "81.6% of Next.js sites were cited by at least one AI platform. 48.0% of WordPress sites were cited by at least one AI platform. Next.js sites averaged 2.29 citations per site vs WordPress at 1.02.",
      "That's not a marginal difference. Next.js sites were cited at nearly double the rate.",
      "## What the AI Platforms Actually Recommended",
      "We asked all three platforms questions that real people ask every day — things like \"what are the best telehealth platforms,\" \"what apps help with anxiety and meditation,\" and \"what are the best health wearables.\"",
      "ChatGPT was the most selective — and the most brutal for WordPress. When someone asks ChatGPT for a recommendation, it names 5-7 brands and moves on. The brands it chose? Overwhelmingly Next.js: Peloton, Strava, Calm, Headspace, GoodRx, Equinox, Dexcom. WordPress sites were largely invisible. These are companies that invested in modern web architectures, and ChatGPT rewards that investment by citing them first.",
      "Claude was the most generous with citations overall, mentioning 103 study sites across 25 queries — but even with a wider net, Next.js sites still dominated with 72% of mentions. WordPress sites that did get cited tended to be large publishers with massive content libraries. Smaller WordPress sites were almost entirely shut out.",
      "Google AI Overviews showed the strongest skew of all. When the AI Overview panel appeared (we tested 10 queries), 78% of study site citations went to Next.js properties. WordPress sites struggled to break through even when they ranked well in traditional organic results. Google's AI clearly favors the kind of fast, well-structured sites that Next.js produces out of the box.",
      "## Why Next.js Sites Win in AI",
      "We dug into the data to understand why this gap exists. It comes down to four things.",
      "## 1. Next.js Powers the Brands AI Trusts",
      "The companies building on Next.js in the health space tend to be the ones investing heavily in product, content, and brand. Think Healthline, GoodRx, Calm, Whoop, Peloton, Dexcom. These aren't small operations — they're category leaders with deep content libraries, millions of users, and strong brand signals across the web.",
      "AI models learn from the internet's collective knowledge. When Healthline shows up in thousands of medical articles, Reddit threads, and \"best of\" lists, AI systems internalize that authority. When a local med spa has a WordPress site with good Yoast SEO scores but limited off-site presence, AI has far less signal to work with.",
      "The takeaway: Next.js has become the default choice for ambitious, tech-forward health companies. That selection bias means the Next.js ecosystem is stacked with exactly the kind of brands AI engines prefer to cite.",
      "## 2. WordPress's SEO Plugins Don't Help with AI",
      "Here's the uncomfortable truth for WordPress loyalists. WordPress sites in our study actually had better traditional SEO scores than Next.js sites. WordPress averaged a 5.64 SEO score (out of 9) compared to 4.73 for Next.js. WordPress sites had more schema markup (1.42 average schema types vs 0.65), more Open Graph tags, and more Twitter cards — largely thanks to Yoast SEO doing the heavy lifting.",
      "None of that translated into more AI citations. Not even close.",
      "This exposes a fundamental problem with the WordPress approach to discoverability. Plugins like Yoast optimize for a search paradigm that's being replaced. Schema markup, meta descriptions, and structured data are table stakes for Google's organic results, but AI citation engines don't care about your Yoast score. They care about brand authority, content depth, and real-world recognition — signals that no plugin can fake.",
      "If your GEO strategy starts and ends with \"install Yoast and add more schema markup,\" you're optimizing for yesterday's algorithms while your Next.js competitors own tomorrow's.",
      "## 3. WordPress Is Slow — and AI Penalizes Slow Sites",
      "Page speed isn't just a UX metric anymore — it's an AI visibility signal. The average WordPress health site in our study loaded in 4-6 seconds on mobile. Next.js sites averaged under 2 seconds. That's not a rounding error. It's the difference between a site AI engines can efficiently crawl and index, and one they deprioritize.",
      "Google has explicitly tied Core Web Vitals to ranking signals, and there's growing evidence that AI systems inherit those same biases. A slow site signals low investment, poor maintenance, and a worse user experience. WordPress's reliance on heavy themes, render-blocking plugins, and unoptimized PHP makes speed an uphill battle. Next.js ships fast by default — server-side rendering, automatic code splitting, image optimization, and edge caching are built into the framework, not bolted on as afterthoughts.",
      "When AI engines evaluate which sites to cite, they're drawing from the same crawl data that penalizes slow pages in traditional search. WordPress sites carry that weight whether they know it or not.",
      "## 4. Next.js Is Built for How AI Evaluates Sites",
      "Next.js gives development teams capabilities that directly produce the kind of web presence AI engines favor: server-side rendering for fast, crawlable pages; API-driven content architectures that scale across channels; superior Core Web Vitals that improve user engagement; and the flexibility to build rich, interactive content experiences that keep visitors on-site longer.",
      "WordPress, by contrast, fights against its own architecture to achieve these things. Plugin bloat tanks performance. PHP-rendered pages are slower to crawl. Theme constraints limit content flexibility. Every optimization requires another plugin, another workaround, another layer of technical debt.",
      "Next.js sites don't just perform better — they create the conditions for building the kind of authoritative, high-performance web presence that AI engines learn to trust. It's the difference between a platform that enables growth and one that constrains it.",
      "## What This Means for Your GEO Strategy",
      "If you're a health industry brand thinking about AI visibility, here's what our data suggests:",
      "If you're on WordPress: Every month you stay on WordPress is a month your competitors on Next.js are pulling further ahead in AI visibility. A migration won't instantly generate citations — you still need brand authority and content depth — but staying on WordPress means fighting uphill with an architecture AI engines aren't built to favor. If you're serious about being discoverable in the AI era, the rebuild conversation needs to happen now, not next year.",
      "If you're building something new: Next.js isn't just the better choice — it's the only serious choice. The health companies dominating AI citations are overwhelmingly on Next.js, and building on the same foundation positions you alongside those brands from day one. You'll attract better development talent, scale faster, and build the kind of performant, content-rich experience that AI engines reward. Starting on WordPress in 2026 is starting behind.",
      "## About This Study",
      "This analysis is based on original research by Driftless AI, testing 99 health industry websites across 25 standardized queries on ChatGPT, Claude, and Google AI Overviews. Sites were classified by CMS platform, brand authority tier, and SEO/schema markup level. Complete data and methodology are available in the companion analysis spreadsheets.",
      "Want to understand where your brand stands in AI search? Get in touch with Driftless AI for a 100% free GEO/AEO audit.",
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return posts.map((p) => p.slug);
}
